In [36]:
import numpy as np
import importlib
import os
import zernike_moment
import generate_descriptor

In [72]:
importlib.reload(zernike_moment)

<module 'zernike_moment' from '/home/ryuhei/zernike_moment/data/program/function/zernike_moment.py'>

In [73]:
atom_info = np.load('/home/ryuhei/zernike_moment/data/working/atom_info.npy').item()

In [74]:
poscar_path = '/home/ryuhei/zernike_moment/data/raw/cohesive/descriptors/A2X3/2085_A2XY2_Bi2Te3/Al-O/POSCAR'

In [75]:
PATH = '/home/ryuhei/zernike_moment/data/working/h_list/5/'
coeff = np.zeros((1, 7))
for i in range(6):
    path = os.path.join(PATH, str(i) + '.npy')
    each = np.load(path)
    coeff = np.vstack((coeff, each))
coeff = coeff[1:]

In [76]:
zd = zernike_moment.ZernikeDescriptor(5)

In [88]:
zd.make_nl_lst()
zd.add_mvalue()
zd.get_coeff_info(coeff)
zd.get_atomic_info(None)
zd.get_moment_val(POSCAR_PATH=poscar_path, cut_off=6)

In [89]:
zd.generate_descriptor()

In [90]:
zd.descriptors[0] - zd.descriptors[1]

array([ 8.87267012e-19+0.j, -1.32272665e-17+0.j, -2.16840434e-18+0.j])

In [99]:
generate_descriptor.generate_each_zernike([5,3], path2, 6)

TypeError: 'numpy.complex128' object cannot be interpreted as an integer

In [96]:
path2 = '/home/ryuhei/zernike_moment/data/raw/cohesive/descriptors/A2X3/2085_A2XY2_Bi2Te3/Al-O/'

In [45]:
for i in range(test.shape[1]):
    for j in range(test.shape[2]):
        vec = test[:,i,j]
        print(np.linalg.norm(vec))

0.0672032207455734j
0.02030995832104388j
0.2337341691529906j
0.11665697804023578j
0.05158731642291707j
0.054106842065697505j
2.0911741245666287j
19.68794004338262j
50.81729257890719j
(0.005476245773749681+0j)
(0.008620892046728867+0j)
(nan+nanj)
0.019450358070362668j
(0.003365932183717733+0j)
(10.017584043503728+0j)
(30.446107324906833+0j)
0.012904243791248667j
0.4282919854078947j
(0.004736485249955147+0j)
(0.11744188653520302+0j)
(3.2073526347786694+0j)
(0.02629727194238274+0j)
(0.7510338133893779+0j)
0.0001558537892003553j
0.06720322074556752j
0.020309958321043056j
0.23373416915298864j
0.11665697804022769j
0.0515873164229168j
0.05410684206569741j
2.091174124566621j
19.687940043382536j
50.81729257890709j
(0.005476245773749749+0j)
(0.008620892046728997+0j)
(nan+nanj)
0.019450358070362068j
(0.003365932183718458+0j)
(10.017584043503815+0j)
(30.446107324906986+0j)
0.012904243791248443j
0.42829198540788965j
(0.004736485249956109+0j)
(0.11744188653520392+0j)
(3.207352634778686+0j)
(0.026297

In [49]:
np.linalg.norm(test[:,1,3])

0.11665697804022769j

In [55]:
hoge = test[:,1,3]

In [71]:
zernike_moment.norm(test).shape

(5, 24)

In [62]:
hoge = hoge.reshape(1, 11)

In [63]:
np.dot(hoge ,np.conj(hoge).T)

array([[(0.5213479604824343+0j)]], dtype=object)

In [65]:
test[:,:,3].shape

(11, 5)

In [66]:
test.shape

(11, 5, 24)

In [231]:
te  * np.conj(te)

9

In [157]:
a = np.array(zd.zernike)

In [158]:
a.shape

(3,)

In [160]:
zd.generate_descriptor()

IndexError: tuple index out of range

In [115]:
zd.zernike[2][3]

array([[-3.82883060e-18+1.79305496e-02j],
       [-8.85774242e-19-1.79305496e-02j],
       [-1.91441530e-18+4.54816438e-02j],
       [-4.05741750e-18-4.54816438e-02j],
       [-2.20771246e-18-2.98507600e-18j]])

In [116]:
np.conj(zd.zernike[2][3])

array([[-3.82883060e-18-1.79305496e-02j],
       [-8.85774242e-19+1.79305496e-02j],
       [-1.91441530e-18-4.54816438e-02j],
       [-4.05741750e-18+4.54816438e-02j],
       [-2.20771246e-18+2.98507600e-18j]])

In [117]:
zd.zernike[0][0].shape

(5, 1)

In [64]:
a = np.hstack((np.zeros((5, 24)), zd.zernike[0][0]))

In [65]:
a.shape

(5, 48)

In [68]:
np.linalg.norm(a, axis=1)

AttributeError: 'complex' object has no attribute 'sqrt'

In [80]:
np.linalg.norm(a, axis=0)

AttributeError: 'float' object has no attribute 'sqrt'

In [84]:
np.linalg.norm(np.array(([1,2], [1+2j])))

TypeError: can't multiply sequence by non-int of type 'list'

In [1]:
import numpy as np

In [2]:
vec = np.array([1+1j, 3])

In [3]:
vec

array([1.+1.j, 3.+0.j])

In [4]:
np.linalg.norm(vec)

3.3166247903554

In [6]:
matrix = np.vstack((vec, np.array([2+3j, 4j])))

In [7]:
matrix.shape

(2, 2)

In [8]:
matrix

array([[1.+1.j, 3.+0.j],
       [2.+3.j, 0.+4.j]])

In [9]:
np.linalg.norm(matrix, axis=0)

array([3.87298335, 5.        ])