In [1]:
import numpy as np
import importlib
import os
import zernike_moment
import generate_descriptor

In [4]:
atom_info = np.load('/home/ryuhei/zernike_moment/data/working/atom_info.npy').item()

In [5]:
poscar_path = '/home/ryuhei/zernike_moment/data/raw/cohesive/descriptors/A2X3/2085_A2XY2_Bi2Te3/Al-O/POSCAR'

In [6]:
PATH = '/home/ryuhei/zernike_moment/data/working/h_list/5/'
coeff = np.zeros((1, 7))
for i in range(6):
    path = os.path.join(PATH, str(i) + '.npy')
    each = np.load(path)
    coeff = np.vstack((coeff, each))
coeff = coeff[1:]

In [7]:
zd = zernike_moment.ZernikeDescriptor(5)

In [8]:
# Use only struct information
zd.make_nl_lst()
zd.add_mvalue()
zd.get_coeff_info(coeff)
zd.get_atomic_info(None)
zd.get_moment_val(POSCAR_PATH=poscar_path, cut_off=6)
zd.generate_descriptor()

In [9]:
zd.descriptors

array([[3.94613723e-02, 2.03423690e-01, 1.81748472e-01],
       [3.94613723e-02, 2.03423690e-01, 1.81748472e-01],
       [8.30686301e-02, 2.70792405e-01, 2.60627657e-01],
       [8.30686301e-02, 2.70792405e-01, 2.60627657e-01],
       [6.34874646e-09, 7.82653641e-09, 3.64424706e-09]])

In [10]:
conp = np.load('/home/ryuhei/descriptors/cohesive/zernike/only_zernike/each_atom/6/atomic_descriptors.npy')

In [21]:
conp[0][9:12]

array([0.0015572 , 0.0413812 , 0.03303251])

In [17]:
zd.descriptors[0]

array([0.03946137, 0.20342369, 0.18174847])

0.033032506347340895

In [67]:
# Use atom information
zd.make_nl_lst()
zd.add_mvalue()
zd.get_coeff_info(coeff)
zd.get_atomic_info(atom_info)
zd.get_moment_val(POSCAR_PATH=poscar_path, cut_off=6)
zd.generate_descriptor()

In [68]:
zd.descriptors

array([[2.24442183e-01, 1.03429873e-01, 4.65315155e-02, 3.28930463e-01,
        9.23078676e-02, 9.75829700e-02, 7.26218762e-01, 1.88105443e+00,
        2.57715248e+00, 6.42006333e-02, 7.60145818e-02,            nan,
        6.92359176e-02, 7.44755749e-02, 2.59780425e+00, 4.54192958e+00,
        3.56406986e-02, 8.05039766e-02, 1.08920440e-01, 2.82495881e-01,
        1.47806643e+00, 1.34055592e-01, 7.78189768e-01, 8.20931752e-03,
        6.35036613e-01, 3.11768051e-01, 7.86733017e-01, 9.05948199e-01,
        3.40734853e-01, 3.47483728e-01, 2.10334215e+00, 6.61890727e+00,
        1.08468510e+01, 1.37193738e-01, 1.34136266e-01,            nan,
        2.59832563e-01, 1.87511331e-01, 3.88622462e+00, 6.57576215e+00,
        1.94127713e-01, 1.06827604e+00, 2.78407115e-01, 4.03089160e-01,
        2.08503283e+00, 1.86313987e-01, 1.73208348e+00, 1.74263674e-02,
        5.93559688e-01, 2.89218126e-01, 6.90267736e-01, 8.49731895e-01,
        2.86798320e-01, 2.91610946e-01, 1.72693784e+00, 5.548901

In [69]:
zd.descriptors.shape

(5, 72)

In [70]:
zd.descriptors[0]

array([2.24442183e-01, 1.03429873e-01, 4.65315155e-02, 3.28930463e-01,
       9.23078676e-02, 9.75829700e-02, 7.26218762e-01, 1.88105443e+00,
       2.57715248e+00, 6.42006333e-02, 7.60145818e-02,            nan,
       6.92359176e-02, 7.44755749e-02, 2.59780425e+00, 4.54192958e+00,
       3.56406986e-02, 8.05039766e-02, 1.08920440e-01, 2.82495881e-01,
       1.47806643e+00, 1.34055592e-01, 7.78189768e-01, 8.20931752e-03,
       6.35036613e-01, 3.11768051e-01, 7.86733017e-01, 9.05948199e-01,
       3.40734853e-01, 3.47483728e-01, 2.10334215e+00, 6.61890727e+00,
       1.08468510e+01, 1.37193738e-01, 1.34136266e-01,            nan,
       2.59832563e-01, 1.87511331e-01, 3.88622462e+00, 6.57576215e+00,
       1.94127713e-01, 1.06827604e+00, 2.78407115e-01, 4.03089160e-01,
       2.08503283e+00, 1.86313987e-01, 1.73208348e+00, 1.74263674e-02,
       5.93559688e-01, 2.89218126e-01, 6.90267736e-01, 8.49731895e-01,
       2.86798320e-01, 2.91610946e-01, 1.72693784e+00, 5.54890139e+00,
      

In [71]:
zd.descriptors[1]

array([2.24442183e-01, 1.03429873e-01, 4.65315155e-02, 3.28930463e-01,
       9.23078676e-02, 9.75829700e-02, 7.26218762e-01, 1.88105443e+00,
       2.57715248e+00, 6.42006333e-02, 7.60145818e-02,            nan,
       6.92359176e-02, 7.44755749e-02, 2.59780425e+00, 4.54192958e+00,
       3.56406986e-02, 8.05039766e-02, 1.08920440e-01, 2.82495881e-01,
       1.47806643e+00, 1.34055592e-01, 7.78189768e-01, 8.20931752e-03,
       6.35036613e-01, 3.11768051e-01, 7.86733017e-01, 9.05948199e-01,
       3.40734853e-01, 3.47483728e-01, 2.10334215e+00, 6.61890727e+00,
       1.08468510e+01, 1.37193738e-01, 1.34136266e-01,            nan,
       2.59832563e-01, 1.87511331e-01, 3.88622462e+00, 6.57576215e+00,
       1.94127713e-01, 1.06827604e+00, 2.78407115e-01, 4.03089160e-01,
       2.08503283e+00, 1.86313987e-01, 1.73208348e+00, 1.74263674e-02,
       5.93559688e-01, 2.89218126e-01, 6.90267736e-01, 8.49731895e-01,
       2.86798320e-01, 2.91610946e-01, 1.72693784e+00, 5.54890139e+00,
      